services:
  cloudflared:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/cloudflare.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
  anythingllm:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/anythingllm-icon.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
